apiVersion: v2
name: open-imis
description: A Helm chart for OpenIMIS
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
- name: db
  version: 0.1.0
  repository: file://./charts/db
  condition: db.enabled
#- name: backend
#  version: 0.1.0
#  repository: file://./charts/backend
#  condition: backend.enabled
#- name: frontend
#  version: 0.1.0
#  repository: file://./charts/frontend
#  condition: frontend.enabled
#- name: gateway
#  version: 0.1.0
#  repository: file://./charts/gateway
#  condition: gateway.enabled
#- name: worker
#  version: 0.1.0
#  repository: file://./charts/worker
#  condition: worker.enabled
#- name: rabbitmq
#  version: 0.1.0
#  repository: file://./charts/rabbitmq
#  condition: rabbitmq.enabled
#- name: restapi
#  version: 0.1.0
#  repository: file://./charts/restapi
#  condition: restapi.enabled