apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    run: backend
  namespace: open-imis
spec:
  type: ClusterIP
  selector:
    run: backend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: tls